# Generated by Django 5.2.4 on 2025-07-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
