# Generated by Django 5.2.4 on 2025-07-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
