# Generated by Django 5.2.4 on 2025-08-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_project_alter_task_status_taskdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default_img.jpeg', null=True, upload_to='tasks_asset'),
        ),
    ]
